parameters:
    locale: 'pl'

imports:
    - { resource: vendors.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    HomePL\TermUploader\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    HomePL\TermUploader\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

#    App\Validator\Constraints\CorrectFilenameValidator:
#        tags:
#            - { name: validator.constraint_validator }

    HomePL\TermUploader\ConfigVendors:
        arguments:
            $vendors: '%vendors%'

